theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Cybersecurity 21-22 summary
show_downloads: true
description: Summary of the Cybersecurity course @ Unibo 2021/2022